os: Visual Studio 2015

platform: x64

build: off

install:
  - choco install rakudostar
  - SET PATH=C:\rakudo\bin;C:\rakudo\share\perl6\site\bin;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%
  - zef --verbose --force-install install .

shallow_clone: true

branches:
  only:
  - master
