os: Visual Studio 2015

platform: x64

build: off

install:
  - choco install strawberryperl
  - cd %APPVEYOR_BUILD_FOLDER%
  - zef --verbose --depsonly install .

test_script:
  - perl6 -e 'say "1..1\nok 1"'

shallow_clone: true

branches:
  only:
  - master
